[loader]
".md" = "text"

[run]
bun = true

[test]
preload = ["./test/setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 1.0, functions = 1.0, statements = 1.0 }
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/test/**", "**/*.test.ts", "**/fixtures/**", "**/var/folders/**"]
